import '../styles/globals.css'
import Head from "next/head";
import Navbar from '../components/Navbar'
import 'bootstrap-icons/font/bootstrap-icons.css'

function MyApp({ Component, pageProps }) {
  return <>
    <Head>
      <title>Daily Learning | Aarush Popli</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="keywords" content="blog, nestjs, learning" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar />
    <Component {...pageProps} />
  </>
}

export default MyApp
